import { createGasto } from "@database/controllers/gasto";

const gastos = [
  {
    dimension: "38101136",
    programa: "CHARLA BELCORP",
    fecha: "10/09/2021",
    factura: 1857,
    proveedor: "CASTRO VALENIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 60,
    iva: 12,
    valorConIva: "67,2",
    observacion: "HORA DE CHAARLA DE MOTIVACION-BELCORP 25 DE AGOSTO",
    req: "165-21",
  },
  {
    dimension: "38101123",
    programa: "UTPL VENTA CONSULTIVA Y PERSUASIVA",
    fecha: "01/07/2021",
    factura: 364,
    proveedor: "ORIOL CABANE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 800,
    iva: 12,
    valorConIva: "896",
    observacion:
      "10 HORAS DE CLASES VIRTUALES DEL PROGRAMA VENTA CONSULTIVA Y PERSUASIVA PARA EL CENTRO SANTO DOMINGO – UTPL",
    req: "95-21",
  },
  {
    dimension: "38101133",
    programa: "UTPL ACTUALIZACION DE SSE",
    fecha: "9/13/2021",
    factura: 9377,
    proveedor: "RUIZ MACIAS DONNY MICHEL",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 400,
    iva: 12,
    valorConIva: "448",
    observacion: "PAGO POR 200 CERTIFICADOS",
    req: "169-21",
  },
  {
    dimension: "38101133",
    programa: "UTPL ACTUALIZACION DE SSE",
    fecha: "04/08/2021",
    factura: 37,
    proveedor: "ACOSTA MUÑOZ LUIS ENRIQUE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion:
      "HONORARIOS APOYO ACADEMICO PARA LOS PROGRAMAS ACTUALIZACION DE DATOS UTPL Y CARGILL",
    req: "136-21",
  },
  {
    dimension: "38101133",
    programa: "UTPL ACTUALIZACION DE SSE",
    fecha: "04/08/2021",
    factura: 1362,
    proveedor: "CALLE ULLOA LAURA YAMILE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 80,
    iva: 12,
    valorConIva: "89,6",
    observacion:
      "2 HORAS  TALLER TERAPIA DE LA RISA DEL PROGRAMA, DEL 7 AL 8 DE JULIO",
    req: "133-21",
  },
  {
    dimension: "38101133",
    programa: "UTPL ACTUALIZACION DE SSE",
    fecha: "03/08/2021",
    factura: 38,
    proveedor: "GARZON SILVA ASTRID",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 600,
    iva: 12,
    valorConIva: "672",
    observacion:
      "12 HORAS VIRTUALES DEL TALLER GESTION DE LAS EMOCIONES DEL 17, 25 Y 30 DE JUNIO",
    req: "131-21",
  },
  {
    dimension: "38101133",
    programa: "UTPL ACTUALIZACION DE SSE",
    fecha: "7/19/2021",
    factura: 593,
    proveedor: "RAMIREZ MANRIQUE MAURICIO ALFONSO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: "535,71",
    iva: 12,
    valorConIva: "600",
    observacion:
      "SERVICIOS DE APOYO EN EL DEPARTAMENTO FINANCIERO DEL 14 DE JUNIO AL 14 DE JULIO DEL 2021",
    req: "122-21",
  },
  {
    dimension: "38101133",
    programa: "UTPL ACTUALIZACION DE SSE",
    fecha: "7/20/2021",
    factura: 74,
    proveedor: "GONZALEZ HUERTA MARIA ESTHER",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 100,
    iva: 12,
    valorConIva: "112",
    observacion:
      "HORAS VIRTUALES DEL TALLER MANAGEMENT 3.0: EL NUEVO MODELO DE LIDERAZGO Y GESTIÓN DE EQUIPOS PARA LOS DIRECTORES DE CARRERA – UTPL",
    req: "108-21",
  },
  {
    dimension: "38101133",
    programa: "UTPL ACTUALIZACION DE SSE",
    fecha: "7/19/2021",
    factura: 413,
    proveedor: "AGUIRRE FLORES DIEGO NICOLAY",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion:
      "HORAS VIRTUALES DE TALLER CUSTOMER EXPERIENCE DEL PROGRAMA DE ACTUALIZACIÓN DE SERVICIOS  STUDIANTILES PARA LOS CENTROS UTPL",
    req: "107-21",
  },
  {
    dimension: "38101133",
    programa: "UTPL ACTUALIZACION DE SSE",
    fecha: "7/16/2021",
    factura: 6,
    proveedor: "SUAREZ MURILLO MARINA PENELOPE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 600,
    iva: 12,
    valorConIva: "672",
    observacion:
      "SERVICIOS DE APOYO ACADÉMICO AL PROGRAMA DE ACTUALIZACIÓN DE PROCESOS SSE UTPL",
    req: "114-21",
  },
  {
    dimension: "38101132",
    programa: "UTPL DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "9/13/2021",
    factura: 9377,
    proveedor: "RUIZ MACIAS DONNY MICHEL",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 72,
    iva: 12,
    valorConIva: "80,64",
    observacion: "CERTIFICADOS",
    req: "169-21",
  },
  {
    dimension: "38101132",
    programa: "UTPL DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "01/09/2021",
    factura: 347,
    proveedor: "MARRIOTT CHAVEZ LUIS ALBERTO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 270,
    iva: 12,
    valorConIva: "302,4",
    observacion:
      "6 HORAS DE CLASE VIRTUALES  DEL CERTIFICADO PRODUCT THINKING LAB DEL DIPLOMADO EN TRANSFORMACION DIGITAL",
    req: "142-21",
  },
  {
    dimension: "38101132",
    programa: "UTPL DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "01/09/2021",
    factura: 30,
    proveedor: "ALBAN BAEZ ANDREA BELEN",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 270,
    iva: 12,
    valorConIva: "302,4",
    observacion:
      "6 HORAS DE CLASE VIRTUAL DEL CERTIFICADO LIDERAZGO Y CULTURA DIGITAL DEL DIPLOMADO TRANSFORMACIÓN DIGITAL DEL 14, 16 Y 18 DE JUNIO",
    req: "130-21",
  },
  {
    dimension: "38101132",
    programa: "UTPL DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "7/15/2021",
    factura: 114,
    proveedor: "SANCHEZ RODRIGUEZ AMINAEL",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 740,
    iva: 12,
    valorConIva: "828,8",
    observacion:
      "DISEÑO DE CONTENIDO DEL CERTIFICADO ESTRATEGIA EXPONENCIAL DEL DIPLOMADO TRANSFORMACIÓN DIGITAL",
    req: "111-21",
  },
  {
    dimension: "38101132",
    programa: "UTPL DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "09/06/2021",
    factura: 8,
    proveedor: "CONNECTEDTHINGS SOLUCIONES TECNOLOGICAS CIA.LTDA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 850,
    iva: 12,
    valorConIva: "952",
    observacion:
      "PAGO EL 50% RESTANTE POR 10 HORAS DE PORFESOR NACIONAL EN EL PROGRAMA DE TRANSFORMACION DIGITAL UTPL",
    req: "75-21",
  },
  {
    dimension: "38101132",
    programa: "UTPL DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "02/06/2021",
    factura: 7,
    proveedor: "CONNECTEDTHINGS SOLUCIONES TECNOLOGICAS CIA.LTDA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 850,
    iva: 12,
    valorConIva: "952",
    observacion:
      "PAGO EL 50% POR 10 HORAS DE PORFESOR NACIONAL EN EL PROGRAMA DE TRANSFORMACION DIGITAL UTPL",
    req: "63-21",
  },
  {
    dimension: "38101131",
    programa: "UTPL MANEJO DE HERRAMIENTAS DIGITALES",
    fecha: "9/13/2021",
    factura: 9377,
    proveedor: "RUIZ MACIAS DONNY MICHEL",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 150,
    iva: 12,
    valorConIva: "168",
    observacion: "PAGO POR 15 CERTIFICADOS HERRAMIENTAS DIGITALES",
    req: "169-21",
  },
  {
    dimension: "38101131",
    programa: "UTPL MANEJO DE HERRAMIENTAS DIGITALES",
    fecha: "01/09/2021",
    factura: 68,
    proveedor: "AGUILAR PALACIOS MARÍA CAMILA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 720,
    iva: 12,
    valorConIva: "806,4",
    observacion:
      "144 HORAS DE APOYO LOGÍSTICO DEL PROGRAMA HERRAIENTAS DIGITALES UTPL",
    req: "143-21",
  },
  {
    dimension: "38101131",
    programa: "UTPL MANEJO DE HERRAMIENTAS DIGITALES",
    fecha: "01/07/2021",
    factura: 137,
    proveedor: "ARMIJOS CABRERA MARIA EUGENIA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 960,
    iva: 12,
    valorConIva: "1075,2",
    observacion:
      "HORAS DE CLASES VIRTUALES DEL PROGRAMA HERRAMIENTAS DIGITALES TECNOLOGICAS PARA EL CENTRO DE LOJA - UTPL",
    req: "91-21",
  },
  {
    dimension: "38101131",
    programa: "UTPL MANEJO DE HERRAMIENTAS DIGITALES",
    fecha: "7/19/2021",
    factura: 139,
    proveedor: "GRANIZO JARAMILLO JORGE LUIS",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 1200,
    iva: 12,
    valorConIva: "1344",
    observacion:
      "HORAS DE CLASES VIRTUALES DEL PROGRAMA HERRAMIENTAS DIGITALES PARA EL CENTRO REGIONAL CUENCA - UTPL",
    req: "96-21",
  },
  {
    dimension: "38101131",
    programa: "UTPL MANEJO DE HERRAMIENTAS DIGITALES",
    fecha: "7/19/2021",
    factura: 138,
    proveedor: "GRANIZO JARAMILLO JORGE LUIS",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 150,
    iva: 12,
    valorConIva: "168",
    observacion: "POR 24 HORAS DE CLASES VIRTUALES CENTRO REGIONAL QUITO",
    req: "80-21",
  },
  {
    dimension: "38101131",
    programa: "UTPL MANEJO DE HERRAMIENTAS DIGITALES",
    fecha: "7/19/2021",
    factura: 138,
    proveedor: "GRANIZO JARAMILLO JORGE LUIS",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 1200,
    iva: 12,
    valorConIva: "1344",
    observacion: "POR 24 HORAS DE CLASES VIRTUALES CENTRO REGIONAL QUITO",
    req: "80-21",
  },
  {
    dimension: "38101130",
    programa: "CLPG HACEMOS PAIS",
    fecha: "10/25/2021",
    factura: 24,
    proveedor: "VASQUEZ ESPINOSA GABRIELA ALEJANDRA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 600,
    iva: 12,
    valorConIva: "672",
    observacion:
      "APOYO AL DEPARTAMENTO ACADEMICO DEL 28 DE AGOSTO AL 27 DE SEPTIEMBRE",
    req: "222-21",
  },
  {
    dimension: "38101130",
    programa: "CLPG HACEMOS PAIS",
    fecha: "03/09/2021",
    factura: 19,
    proveedor: "VASQUEZ ESPINOSA GABRIELA ALEJANDRA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 600,
    iva: 12,
    valorConIva: "672",
    observacion:
      "APOYO AL DEPARTAMENTO ACADEMICO DEL 28 DE JULIO AL 27 DE AGOSTO",
    req: "128-21",
  },
  {
    dimension: "38101130",
    programa: "CLPG HACEMOS PAIS",
    fecha: "02/08/2021",
    factura: 16,
    proveedor: "VASQUEZ ESPINOSA GABRIELA ALEJANDRA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 600,
    iva: 12,
    valorConIva: "672",
    observacion:
      "APOYO AL DEPARTAMENTO ACADEMICO DEL 28 DE JUNIO AL 28 de JULIO",
    req: "128-21",
  },
  {
    dimension: "38101130",
    programa: "CLPG HACEMOS PAIS",
    fecha: "01/07/2021",
    factura: 12,
    proveedor: "VASQUEZ ESPINOSA GABRIELA ALEJANDRA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: "535,71",
    iva: 12,
    valorConIva: "600",
    observacion: "APOYO AL DEPARTAMENTO ACADEMICO DEL 27 DE MAYO 27 de JUNIO",
    req: "90-21",
  },
  {
    dimension: "38101130",
    programa: "CLPG HACEMOS PAIS",
    fecha: "03/06/2021",
    factura: 207,
    proveedor: "ENRIQUEZ DIAZ GEOVANNA GABRIELA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 1680,
    iva: 12,
    valorConIva: "1881,6",
    observacion:
      "POR LA ELABORACION DE 14 VIDEOS PARA EL PROGRAMA HACIENDO PAIS",
    req: "73-21",
  },
  {
    dimension: "38101130",
    programa: "CLPG HACEMOS PAIS",
    fecha: "03/06/2021",
    factura: 22,
    proveedor: "BAPTISTA CARRERO ILDEMARO JOSE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 1680,
    iva: 12,
    valorConIva: "1881,6",
    observacion:
      "POR LA ELABORACION DE 14 VIDEOS PARA EL PROGRAMA HACIENDO PAIS",
    req: "74-21",
  },
  {
    dimension: "38101128",
    programa: "UTPL IMAGEN PERSONAL Y CORPORATIVA",
    fecha: "04/10/2021",
    factura: 46,
    proveedor: "PEREZ GUZMAN ANAHI SUSANA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 640,
    iva: 12,
    valorConIva: "716,8",
    observacion: "SE CANCELA POR LA LOGISTICA DE LOS MESOS MAYO-JUNIO",
    req: "193-21",
  },
  {
    dimension: "38101128",
    programa: "UTPL IMAGEN PERSONAL Y CORPORATIVA",
    fecha: "12/08/2021",
    factura: 112,
    proveedor: "MILA ALMACHE OSCAR IVAN",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: "190,5",
    iva: 12,
    valorConIva: "213,36",
    observacion: "SE CANCELA 127 CERTIFICADOS DEL PROGRAMA IMAGEN CORPORATIVO",
    req: "145-21",
  },
  {
    dimension: "38101139",
    programa: "BANCO DE LOJA ANALISIS FINANCIERO Y CREDITO",
    fecha: "10/18/2021",
    factura: 3,
    proveedor: "IZQUIERDO MONTOYA GONZALO LEONARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 150,
    iva: 12,
    valorConIva: "168",
    observacion:
      "HORA CHARLA META CERO Y DESARROLLO SOSTENIBLE DEL PROGRAMA BANCO DE LOJA",
    req: "209-21",
  },
  {
    dimension: "38101139",
    programa: "BANCO DE LOJA ANALISIS FINANCIERO Y CREDITO",
    fecha: "10/19/2021",
    factura: 32,
    proveedor: "JOSÉ ANTONIO GIL",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 2110,
    iva: 12,
    valorConIva: "2363,2",
    observacion:
      "16 HORAS DE CAPACITACIÓN PROGRAMA ANÁLISIS FINANCIERO Y CRÉDITO, DISEÑO DE MATERIAL, LEVANTAMIENTO DE  INFORMACIÓN Y CONSTRUCCIÓN DE CASOS",
    req: "212-21",
  },
  {
    dimension: "38101139",
    programa: "BANCO DE LOJA ANALISIS FINANCIERO Y CREDITO",
    fecha: "12/09/2021",
    factura: 1037,
    proveedor: "EDILOJA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: "216,22",
    iva: 12,
    valorConIva: "242,17",
    observacion:
      "SERVICIOS DE IMPREIÓN DE UN CERTIFICADO DIGITAL, LIBRETAS PARA CLIENTES",
    req: "153-21",
  },
  {
    dimension: "38101128",
    programa: "UTPL IMAGEN PERSONAL Y CORPORATIVA",
    fecha: "04/08/2021",
    factura: 983,
    proveedor: "EDILOJA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 331,
    iva: 12,
    valorConIva: "370,72",
    observacion:
      "IMPRESION DE 371 CERTIFICADOS PARA EDUCACION CONTINUA ACUERDO LLEGADO CON ROSSANA",
    req: "139-21",
  },
  {
    dimension: "38101128",
    programa: "UTPL IMAGEN PERSONAL Y CORPORATIVA",
    fecha: "12/07/2021",
    factura: 29,
    proveedor: "JUMBO GAONA DASHELLY JOHELIA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 80,
    iva: 0,
    valorConIva: "80",
    observacion:
      "HORAS DE APOYO LOGÍSTICO DEL CURSO DE IMAGEN CORPORATIVA DEL 25 AL 28 DE MAYO DEL 2021",
    req: "103-21",
  },
  {
    dimension: "38101128",
    programa: "UTPL IMAGEN PERSONAL Y CORPORATIVA",
    fecha: "12/07/2021",
    factura: 30,
    proveedor: "JUMBO GAONA DASHELLY JOHELIA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 80,
    iva: 0,
    valorConIva: "80",
    observacion:
      "HORAS DE APOYO LOGÍSTICO DEL CURSO DE IMAGEN CORPORATIVA DEL 25 AL 28 DE MAYO DEL 2021- RUBRO PERSONA DE LOGÍSTICA",
    req: "103-21",
  },
  {
    dimension: "38101128",
    programa: "UTPL IMAGEN PERSONAL Y CORPORATIVA",
    fecha: "6/18/2021",
    factura: 53,
    proveedor: "MONTEVERDE BRAVO PAMELA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 150,
    iva: 12,
    valorConIva: "168",
    observacion: "DISEÑO DE CONTENIDO DEL PORGRAMA",
    req: "83-21",
  },
  {
    dimension: "38101128",
    programa: "UTPL IMAGEN PERSONAL Y CORPORATIVA",
    fecha: "6/18/2021",
    factura: 53,
    proveedor: "MONTEVERDE BRAVO PAMELA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 800,
    iva: 12,
    valorConIva: "896",
    observacion:
      "16 HORAS VIRTUALES DEL MOUDLO IMAGEN CORPRATIVA DEL 25 AL 28 DE MAYO",
    req: "83-21",
  },
  {
    dimension: "38101127",
    programa: "BANCO PICHINCHA LIDERAZGO COMERCIAR RIESGO Y CREDITO",
    fecha: "01/09/2021",
    factura: 31,
    proveedor: "GILD SANTIAGO JOSE ANTONIO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 1440,
    iva: 12,
    valorConIva: "1612,8",
    observacion: "24 HORAS DE CAPACITACION RIESGO Y ANALISIS FINANCIERO",
    req: "149-21",
  },
  {
    dimension: "38101127",
    programa: "BANCO PICHINCHA LIDERAZGO COMERCIAR RIESGO Y CREDITO",
    fecha: "01/09/2021",
    factura: 31,
    proveedor: "GILD SANTIAGO JOSE ANTONIO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion: "1 DISEÑO DE MATERIAL",
    req: "149-21",
  },
  {
    dimension: "38101127",
    programa: "BANCO PICHINCHA LIDERAZGO COMERCIAR RIESGO Y CREDITO",
    fecha: "01/09/2021",
    factura: 31,
    proveedor: "GILD SANTIAGO JOSE ANTONIO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 1000,
    iva: 12,
    valorConIva: "1120",
    observacion: "LEVANTAMIENTO DE INFORMACION CONSTRUCCION DE CASOS",
    req: "149-21",
  },
  {
    dimension: "38101122",
    programa: "UTPL GESTION DE LAS EMOSIONES PROCURADURIA",
    fecha: "01/06/2021",
    factura: 1816,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "4 HORAS DE CAPACITACION DEL 22 AL 23 DE ABRIL DEL 2021",
    req: "44-21",
  },
  {
    dimension: "38101122",
    programa: "UTPL GESTION DE LAS EMOSIONES PROCURADURIA",
    fecha: "01/06/2021",
    factura: 1816,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 150,
    iva: 12,
    valorConIva: "168",
    observacion: "DISEÑO DEL MATERIAL PARA EL MODULO IMPARTIDO",
    req: "44-21",
  },
  {
    dimension: "38101121",
    programa: "UTPL GESTION DE LAS EMOSIONES SANTO DOMINGO",
    fecha: "6/16/2021",
    factura: 1824,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "4 HORAS DE CAPACITACION DEL 14 Y 14 DE MAYO EN SANTO DOMINGO",
    req: "44-21",
  },
  {
    dimension: "38101140",
    programa: "OIM EMPRENDIMIENTO SOSTENIBLE",
    fecha: "10/22/2021",
    factura: 129,
    proveedor: "ACOSTA MUÑOZ LUIS ENRIQUE",
    categoria: "HONORARIOS ACADÉMICOS",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 600,
    iva: 12,
    valorConIva: "672",
    observacion:
      "PAGO POR APOYO EN EL DEPARTAMENTO ACADÉMICO DESDE EL 6 DE SEPTIEMBRE AL 6 DE OCTUBRE DEL 2021",
    req: "217-21",
  },
  {
    dimension: "38101140",
    programa: "OIM EMPRENDIMIENTO SOSTENIBLE",
    fecha: "10/20/2021",
    factura: 1557854,
    proveedor: "VERONICA VELÁSQUEZ",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "4,46",
    iva: 12,
    valorConIva: "5",
    observacion: "PAGO POR RECARGA DE 5 DOLARES A LUIS  ACOSTA",
    req: "213-21",
  },
  {
    dimension: "38101140",
    programa: "OIM EMPRENDIMIENTO SOSTENIBLE",
    fecha: "10/15/2021",
    factura: 1229,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "180,85",
    iva: 12,
    valorConIva: "202,55",
    observacion: "PAUTA EMPRENDIMIENTO SOSTENIBLE SEPTIEMBRE",
    req: "204-21",
  },
  {
    dimension: "38101140",
    programa: "OIM EMPRENDIMIENTO SOSTENIBLE",
    fecha: "10/14/2021",
    factura: 1886,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 300,
    iva: 12,
    valorConIva: "336",
    observacion: "6 HORAS PROGRAMA DE EMPRENDIMIENTO SOSTENIBLE OIM",
    req: "207-21",
  },
  {
    dimension: "38101119",
    programa: "GLOBALY COOL",
    fecha: "10/15/2021",
    factura: 1229,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "24,7",
    iva: 12,
    valorConIva: "27,66",
    observacion: "PAUTA DE MEDIOS GLOBALLY COOL SEPTIEMBRE",
    req: "204-21",
  },
  {
    dimension: "38101119",
    programa: "GLOBALY COOL",
    fecha: "9/20/2021",
    factura: 1189,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 525,
    iva: 12,
    valorConIva: "588",
    observacion:
      "PAUTAS DE MEDIOS DE INNOVACION COMERCIAL ABRIL, PAUTA DE MEDIOS DIPLOMADO HABILIDADES DIRECTIVAS Y PAUTA DE MEDIOS GLOBALY COOL",
    req: "174-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "10/15/2021",
    factura: 1229,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "299,99",
    iva: 12,
    valorConIva: "335,99",
    observacion: "PAUTAS DE MEDIOS DIPLOMADO HABILIDADES DIRECTIVAS",
    req: "204-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "10/14/2021",
    factura: 1868,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 100,
    iva: 12,
    valorConIva: "112",
    observacion: "2 HORAS PROGRAMA DE HABILIDADES DIRECTIVAS",
    req: "207-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "10/13/2021",
    factura: 58,
    proveedor: "IN CONTAC",
    categoria: "MARKETING",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion:
      "PAUTAS EN LOS PROGRAMAS DE INNOVACIÓN COMERCIAL Y HABILIDADES GERENCIALES, CALL CENTER DEL MES DE AGOSTO",
    req: "201-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "07/10/2021",
    factura: 56,
    proveedor: "IN CONTAC",
    categoria: "SERVICIOS TECNOLOGICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion:
      "SE CANCELA A PROVEEDOR IN CONTAC POR SERVICIOS DE CALL CENTER DURANTE EL MES DE SEPTIEMBRE POR SERVICIO DE PAUTA EN EL PROGRAGRAMA DE HABILIDADES DIRECTIVAS",
    req: "195-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "9/20/2021",
    factura: 1189,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 700,
    iva: 12,
    valorConIva: "784",
    observacion:
      "PAUTAS DE MEDIOS DE INNOVACION COMERCIAL ABRIL, PAUTA DE MEDIOS DIPLOMADO HABILIDADES DIRECTIVAS Y PAUTA DE MEDIOS GLOBALY COOL",
    req: "174-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "7/19/2021",
    factura: 27,
    proveedor: "GILD SANTIAGO JOSE ANTONIO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 350,
    iva: 12,
    valorConIva: "392",
    observacion:
      "DISEÑO INSTRUCCIONAL DEL MÓDULO: FINANZAS PARA LA TOMA DE DECISIONES – DIPLOMADO HABILIDADES DIRECTIVAS",
    req: "121-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "7/15/2021",
    factura: 115,
    proveedor: "SANCHEZ RODRIGUEZ AMINAEL",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 350,
    iva: 12,
    valorConIva: "392",
    observacion:
      "DISEÑO DE CONTENIDO DEL MODULO ANALITICA DE DATOS PARA NEGOCIOS DEL DIPLOMADO HABILIDADES DIRECTIVA",
    req: "112-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "03/06/2021",
    factura: 27,
    proveedor: "VILLALVA CHAVEZ JUAN PABLO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 100,
    iva: 12,
    valorConIva: "112",
    observacion: "RECURSO DE VIRTALIZACION DEL MODULO GESTION DE OPERACIONES",
    req: "47-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "03/06/2021",
    factura: 27,
    proveedor: "VILLALVA CHAVEZ JUAN PABLO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 250,
    iva: 12,
    valorConIva: "280",
    observacion:
      "DISEÑO FICHA INSTRUCCIONAL DEL MODULO GESTION DE OPERACIOES Y CADENA DE SUMINISTROS DEL PROGRAMA",
    req: "47-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "6/18/2021",
    factura: 277,
    proveedor: "PAEZ AGUILAR FRANCISCO JOSE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 350,
    iva: 12,
    valorConIva: "392",
    observacion:
      "FICHA INSTRUCCIONAL Y RECURSOS PARA DEL CONTENIDO MODULO PLANIFICACION ESTRATEGICO",
    req: "88-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "6/18/2021",
    factura: 134,
    proveedor: "ESTEVEZ FERNANDEZ RAUL FEDERICO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 100,
    iva: 12,
    valorConIva: "112",
    observacion:
      "RECURSO PARA LA VIRTUALIZACION DEL CONTENIDO DEL MODULO MARKETING ESTRATEGICO CON  E-COMERCE- GUIN DE VIDEOS, GUION DE RECURSOS INTERACTIVOS interactivos, guion de lecturas y guion de banco de preguntas",
    req: "82-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "6/18/2021",
    factura: 134,
    proveedor: "ESTEVEZ FERNANDEZ RAUL FEDERICO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 250,
    iva: 12,
    valorConIva: "280",
    observacion:
      "FICHA INSTRUCCIONAL DEL MODULO MARKETING STRATEGICO E COMMERCE",
    req: "82-21",
  },
  {
    dimension: "38101117",
    programa: "DIPLOMADO EN HABILIDADES DIRECTIVAS",
    fecha: "4/15/2021",
    factura: 70,
    proveedor: "GONZALEZ HUERTAS MARIA ESTHER",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 350,
    iva: 12,
    valorConIva: "392",
    observacion:
      "PAGO A MARIA ESTHER GONZALEZ PROGRAMA DIPLOMADO EN HABILIDADES GERENCIALES",
    req: "38-21",
  },
  {
    dimension: "38101115-2",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL CICLO II",
    fecha: "04/10/2021",
    factura: 45,
    proveedor: "PEREZ GUZMAN ANAHI SUSANA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 600,
    iva: 12,
    valorConIva: "672",
    observacion: "PAGO POR LOGISTICA DEL MES DE AGOSTO",
    req: "194-21",
  },
  {
    dimension: "38101115-2",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL CICLO II",
    fecha: "9/20/2021",
    factura: 349,
    proveedor: "MARRIOTT CHAVEZ LUIS ALBERTO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 270,
    iva: 12,
    valorConIva: "302,4",
    observacion:
      "6 HORAS DE CLASE VIRTUALES  DEL CERTIFICADO PRODUCT THINKING LAB DEL DIPLOMADO EN TRANSFORMACION DIGITAL CICLO II",
    req: "177-21",
  },
  {
    dimension: "38101115-2",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL CICLO II",
    fecha: "7/19/2021",
    factura: 1144,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "390,54",
    iva: 12,
    valorConIva: "437,4",
    observacion:
      "PAUTA DE MEDIOS INNOVACIÓN COMERCIAL ABRIL PAUTA DE MEDIOS DIPLOMADO EMPRENDIMIENTO BOOTCAMP PAUTA DE MEDIOS TRANSFORMACIÓN DIGITAL",
    req: "118-21",
  },
  {
    dimension: "38101115-2",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL CICLO II",
    fecha: "7/23/2021",
    factura: 27,
    proveedor: "CONNECTEDTHINGS SOLUCIONES TECNOLOGICAS CIA LTDA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 650,
    iva: 12,
    valorConIva: "728",
    observacion:
      "SE CANCELA A PROVEEDOR EL 50% RESTNTE CORRESPONDIENTE A HONORARIOS PROFESOR LOCAL 2 HORAS Y PROFESOR INTERNACIONAL JAIME BARCO 8 HORAS EN EL PROGRAMA TRANSFORMACIÓN DIGITAL.",
    req: "123-21",
  },
  {
    dimension: "38101115-2",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL CICLO II",
    fecha: "01/09/2021",
    factura: 30,
    proveedor: "ALBAN BAEZ ANDREA BELEN",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 270,
    iva: 12,
    valorConIva: "302,4",
    observacion:
      "6 HORAS DE CLASE VIRTUALES  DEL MODULO LIDERAZGO Y CULTURA DIGITAL DEL DIPLOMADO TRANSFORMACIÓN DIGITAL DEL 26,28 Y 29 DE JUNIO EDICION 2",
    req: "130-21",
  },
  {
    dimension: "38101115-2",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL CICLO II",
    fecha: "7/19/2021",
    factura: 29,
    proveedor: "ALBAN BAEZ ANDREA BELEN",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 270,
    iva: 12,
    valorConIva: "302,4",
    observacion:
      "SERVICIOS PROFESIONALES DE LA SESION VIRTUAL DEL CERTIFICADO EN LIDERAZGO Y CULTURA DIGITAL",
    req: "97-21",
  },
  {
    dimension: "38101115-2",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL CICLO II",
    fecha: "12/07/2021",
    factura: 47,
    proveedor: "IN CONTAC",
    categoria: "SERVICIOS TECNOLOGICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion:
      "SE CANCELA A PROVEEDOR IN CONTAC POR SERVICIOS DE CALL CENTER DURANTE EL MES DE JUNIO POR SERVICIO DE PAUTA EN LOS PROGRAMAS DE INNOVACIÓN COMERCIAL Y TRASNFORMACION DIGITAL",
    req: "106-21",
  },
  {
    dimension: "38101115-2",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL CICLO II",
    fecha: "01/07/2021",
    factura: 728,
    proveedor: "CONNECTEDTHINGS SOLUCIONES TECNOLOGICAS CIA LTDA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 650,
    iva: 12,
    valorConIva: "728",
    observacion:
      "SE CANCELA A PROVEEDOR EL 50% INICIAL CORRESPONDIENTE A HONORARIOS PROFESOR LOCAL 2 HORAS Y PROFESOR INTERNACIONAL JAIME BARCO 8 HORAS EN EL PROGRAMA TRANSFORMACIÓN DIGITAL.",
    req: "94-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "7/19/2021",
    factura: 343,
    proveedor: "MARRIOTT CHAVEZ LUIS ALBERTO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 100,
    iva: 12,
    valorConIva: "112",
    observacion:
      "SEGUIMINTO DE CONTINIDO DEL TALLER VIRTUL DEL MÓDULO PRODUCT THINKING",
    req: "79-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "7/19/2021",
    factura: 343,
    proveedor: "MARRIOTT CHAVEZ LUIS ALBERTO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "DESARROLLO DE CONTENIDO DEL MÓDULO PRODUCT THINKING",
    req: "79-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "7/19/2021",
    factura: 343,
    proveedor: "MARRIOTT CHAVEZ LUIS ALBERTO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 270,
    iva: 12,
    valorConIva: "302,4",
    observacion:
      "6 HORAS DE TALLER VIRTUAL DEL CERTIFICADO PRODUCT THINKING LB DEL DIPLOMADO EN TRNSFORMACIÓN DIGITAL",
    req: "79-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "6/18/2021",
    factura: 12,
    proveedor: "CONNECTEDTHINGS SOLUCIONES TECNOLOGICAS CIA.LTDA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 90,
    iva: 12,
    valorConIva: "100,8",
    observacion: "2 HORAS  PAGO PROFESOR NACIONAL 50% RESTANTE",
    req: "89-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "6/18/2021",
    factura: 12,
    proveedor: "CONNECTEDTHINGS SOLUCIONES TECNOLOGICAS CIA.LTDA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 560,
    iva: 12,
    valorConIva: "627,2",
    observacion: "OCHO  HORAS DE PORFESOR INTERNACIONAL 50% RESTANTE",
    req: "89-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "6/17/2021",
    factura: 1118,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 217,
    iva: 12,
    valorConIva: "243,04",
    observacion:
      "PAGO POR PAUTA DE MEDIOS INNOVACIÓN COMERCIAL ABRIL Y PAUT DE MEDIOS DE TRANSFORMACIÓN DIGITAL",
    req: "86-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "5/20/2021",
    factura: 26,
    proveedor: "ALBAN BAEZ ANDREA BELEN",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion:
      "PAGO POR DISEÑO Y DESARROLLO DE MATERIAL MODULO LIDERAZGO Y CULTURA",
    req: "59-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "5/18/2021",
    factura: 35,
    proveedor: "PAZ Y MIÑO LUIS EDUARDO IN CONTACT CENTER",
    categoria: "MARKETING",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion: "PAGO POR SERVICIO DE CALL CENTER DEL MES DE ABRIL",
    req: "50-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "5/18/2021",
    factura: 78,
    proveedor: "CONNECTEDTHINGS SOLUCIONES TECNOLOGICAS CIA.LTDA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 90,
    iva: 12,
    valorConIva: "100,8",
    observacion:
      "PAGO EL 50% POR CUATRO HORAS DE PORFESOR NACIONAL EN EL PROGRAMA DE TRANSFORMACION DIGITAL",
    req: "53-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "5/18/2021",
    factura: 78,
    proveedor: "CONNECTEDTHINGS SOLUCIONES TECNOLOGICAS CIA.LTDA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 560,
    iva: 12,
    valorConIva: "627,2",
    observacion:
      "PAGO EL 50% POR OCHO  HORAS DE PORFESOR NACIONAL EN EL PROGRAMA DE TRANSFORMACION DIGITAL",
    req: "53-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "5/18/2021",
    factura: 1092,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "845,26",
    iva: 12,
    valorConIva: "946,69",
    observacion: "PAGO POR PAUTA DIGITAL TRANSFORMACION DIGITAL MES DE ABRIL",
    req: "55-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "4/16/2021",
    factura: 1055,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "515,2",
    iva: 12,
    valorConIva: "577,02",
    observacion: "PAGO A DAVCASTOR DIGITAL",
    req: "40-21",
  },
  {
    dimension: "38101115",
    programa: "DIPLOMADO EN TRANSFORMACION DIGITAL",
    fecha: "01/04/2021",
    factura: 27,
    proveedor: "PAZ Y MIÑO LUIS EDUARDO IN CONTACT CENTER",
    categoria: "MARKETING",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion: "PAGO POR SERVICIO DE CALL CENTER DEL MES DE MARZO",
    req: "31-21",
  },
  {
    dimension: "38101113",
    programa: "DIPLOMADO EMPRENDIMIENTO INNOVCION AGIL",
    fecha: "02/09/2021",
    factura: 52,
    proveedor: "IN CONTAC",
    categoria: "SERVICIOS TECNOLOGICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion: "FEE GESTIÓN COMERCIAL CALL CENTER MAB MES DE JUNIO 21",
    req: "154-21",
  },
  {
    dimension: "38101113",
    programa: "DIPLOMADO EMPRENDIMIENTO INNOVCION AGIL",
    fecha: "07/09/2021",
    factura: 1183,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "309,45",
    iva: 12,
    valorConIva: "346,58",
    observacion: "PAUTA DE MEDIOS DIPLOMADO",
    req: "161-21",
  },
  {
    dimension: "38101113",
    programa: "DIPLOMADO EMPRENDIMIENTO INNOVCION AGIL",
    fecha: "7/19/2021",
    factura: 1144,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "557,64",
    iva: 12,
    valorConIva: "624,56",
    observacion:
      "PAUTA DE MEDIOS INNOVACIÓN COMERCIAL ABRIL PAUTA DE MEDIOS DIPLOMADO EMPRENDIMIENTO BOOTCAMP PAUTA DE MEDIOS TRANSFORMACIÓN DIGITAL",
    req: "118-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "10/20/2021",
    factura: 370,
    proveedor: "SALAZAR ALMEIDA JUAN FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 400,
    iva: 12,
    valorConIva: "448",
    observacion:
      "16 HORAS DE CLASES VIRTUALES BOOTCAMP DE EMPRENDIMIENTO FUNDACIÓN CHARLES DARWIN",
    req: "214-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "01/10/2021",
    factura: 173,
    proveedor: "ALCIVAR MACIAS ENRIQUE NEPTALI",
    categoria: "TRANSPORTE Y MOVILIZACION",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 30,
    iva: 0,
    valorConIva: "30",
    observacion: "PAGO POR MOVILIZACION TRANSLADO DE ROSANA RUZZA",
    req: "190-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "9/21/2021",
    factura: 172,
    proveedor: "ALCIVAR MACIAS ENRIQUE NEPTALI",
    categoria: "TRANSPORTE Y MOVILIZACION",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 30,
    iva: 0,
    valorConIva: "30",
    observacion:
      "PAGO POR MOVILIZACION TRANSLADO AL AEROPUERTO DE CAMILA AGUILAR Y ROSANA RUZZA",
    req: "185-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "9/20/2021",
    factura: 1140,
    proveedor: "MILA ALMACHE OSCAR",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: "112,5",
    iva: 12,
    valorConIva: "126",
    observacion: "PAGO POR 25 AGENDAS DE DOBLE ANILLO CON PASTA DURA",
    req: "182-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "9/20/2021",
    factura: 1141,
    proveedor: "MILA ALMACHE OSCAR",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 34,
    iva: 12,
    valorConIva: "38,08",
    observacion: "PAGO POR 34 CERTIFICADOS",
    req: "181-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "9/15/2021",
    factura: 7200,
    proveedor: "ATLANTIS TRAVEL",
    categoria: "TRANSPORTE Y MOVILIZACION",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 20,
    iva: 12,
    valorConIva: "22,4",
    observacion: "FEE DE EMISIÓN DE PASAJE AÉREO",
    req: "167-18",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "9/15/2021",
    factura: 7199,
    proveedor: "ATLANTIS TRAVEL",
    categoria: "TRANSPORTE Y MOVILIZACION",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: "54,1",
    iva: 0,
    valorConIva: "54,1",
    observacion: "GASTOS TASAS AEROPORTUARIAS DE ROSSANA RUZZA",
    req: "167-19",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "9/15/2021",
    factura: 7199,
    proveedor: "ATLANTIS TRAVEL",
    categoria: "TRANSPORTE Y MOVILIZACION",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 314,
    iva: 12,
    valorConIva: "351,68",
    observacion: "GASTOS EN PASAJE AREO CON IVA DE ROSSANA RUZZA",
    req: "167-20",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "9/15/2021",
    factura: 7198,
    proveedor: "ATLANTIS TRAVEL",
    categoria: "TRANSPORTE Y MOVILIZACION",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: "54,1",
    iva: 0,
    valorConIva: "54,1",
    observacion: "GASTOS TASAS AEROPORTUARIAS DE CAMILA AGUILAR",
    req: "167-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "9/15/2021",
    factura: 7198,
    proveedor: "ATLANTIS TRAVEL",
    categoria: "TRANSPORTE Y MOVILIZACION",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 314,
    iva: 12,
    valorConIva: "351,68",
    observacion: "GASTOS EN PASAJE AREO CON IVA DE CAMILA AGUILAR",
    req: "167-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "04/08/2021",
    factura: 178,
    proveedor: "SALAZAR ALMEIDA JUAN FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion: "DISEÑO DEL CONTENIDO DE LOS 4 MODULOS",
    req: "134-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "04/08/2021",
    factura: 178,
    proveedor: "SALAZAR ALMEIDA JUAN FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 1000,
    iva: 12,
    valorConIva: "1120",
    observacion: "VIRTUALIZACION DE LOS 4 MODULOS",
    req: "134-21",
  },
  {
    dimension: "38101112",
    programa: "CHARLES DARWIN - GALAPAGOS BOOTCAMP DE EMPRENDIMIENTO",
    fecha: "04/08/2021",
    factura: 178,
    proveedor: "SALAZAR ALMEIDA JUAN FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 1000,
    iva: 12,
    valorConIva: "1120",
    observacion: "20 HORAS VIRTUALES DEL PROGRAMA",
    req: "134-21",
  },
  {
    dimension: "38101109",
    programa: "UTPL GESTION DE LAS EMOCIONES",
    fecha: "9/13/2021",
    factura: 9377,
    proveedor: "RUIZ MACIAS DONNY MICHEL",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 16,
    iva: 12,
    valorConIva: "17,92",
    observacion: "PAGO POR 8 CERTIFICADOS DE GESTION DE LAS EMOCIONES",
    req: "169-21",
  },
  {
    dimension: "38101109",
    programa: "UTPL GESTION DE LAS EMOCIONES",
    fecha: "06/09/2021",
    factura: 75,
    proveedor: "AGUILAR PALACIOS MARIA CAMILA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 260,
    iva: 12,
    valorConIva: "291,2",
    observacion:
      "52 HORAS DE SERVISIOS DIVERSOS POR APOYO LOGÍSTICO PROGRAMA GESTIÓN DE EMOCIONES UTPL",
    req: "157-21",
  },
  {
    dimension: "38101107",
    programa: "UTPL CHARLA DE LIDERAZGO",
    fecha: "9/13/2021",
    factura: 9377,
    proveedor: "RUIZ MACIAS DONNY MICHEL",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 370,
    iva: 12,
    valorConIva: "414,4",
    observacion: "PAGO POR 185 CERTIFICADOS DE CHARLA LIDERAZGO",
    req: "169-21",
  },
  {
    dimension: "38101107",
    programa: "UTPL CHARLA DE LIDERAZGO",
    fecha: "4/13/2021",
    factura: 32,
    proveedor: "GARZON SILVA ASTRID",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 250,
    iva: 12,
    valorConIva: "280",
    observacion: "PAGO A ASTRID GARZON PROGRAMA CHARLAS DE LIDERAZGO UTPL",
    req: "36-21",
  },
  {
    dimension: "38101107",
    programa: "UTPL CHARLA DE LIDERAZGO",
    fecha: "09/03/2021",
    factura: 1794,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 350,
    iva: 12,
    valorConIva: "392",
    observacion: "7 HORAS DE CAPACITACION DEL 01 AL 12 DE FEBRERO",
    req: "19-21",
  },
  {
    dimension: "38101106",
    programa: "ADELCA ESCUELA MODELO DE VENTAS",
    fecha: "04/03/2021",
    factura: 131,
    proveedor: "ESTEVEZ FERNANDEZ RAUL FEDERICO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 1500,
    iva: 12,
    valorConIva: "1680",
    observacion: "30 HORAS DE TALLER PARA EL PROGRAMA",
    req: "17-21",
  },
  {
    dimension: "38101106",
    programa: "ADELCA ESCUELA MODELO DE VENTAS",
    fecha: "04/03/2021",
    factura: 131,
    proveedor: "ESTEVEZ FERNANDEZ RAUL FEDERICO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 2700,
    iva: 12,
    valorConIva: "3024",
    observacion:
      "DISEÑO DEL MODELO DE VENTAS Y TALLER PARA LA FUERZA DE VENTAS",
    req: "17-21",
  },
  {
    dimension: "38101100",
    programa: "CLPG LIDERAZGO Y DESARROLLO DE CAPACIDADES",
    fecha: "03/05/2021",
    factura: 266,
    proveedor: "CEVALLOS SALGADO DIEGO SEBASTIAN",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion:
      "PAGO DE 4 HORAS DE CLASE EN MODULO 2 DESDE EL 26 DE FEBRERO AL 1 DE MARZO",
    req: "43-21",
  },
  {
    dimension: "38101100",
    programa: "CLPG LIDERAZGO Y DESARROLLO DE CAPACIDADES",
    fecha: "4/13/2021",
    factura: 33,
    proveedor: "GARZON SILVA ASTRID",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 100,
    iva: 12,
    valorConIva: "112",
    observacion: "PAGO A ASTRID GARZON PROGRAMA CHARLAS DE LIDERAZGO UTPL",
    req: "36-21",
  },
  {
    dimension: "38101100",
    programa: "CLPG LIDERAZGO Y DESARROLLO DE CAPACIDADES",
    fecha: "12/04/2021",
    factura: 478,
    proveedor: "LARREATEGUI FABARA MARIA GABRIELA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 100,
    iva: 12,
    valorConIva: "112",
    observacion: "PAGO A GABRIELA LARREATEGUI",
    req: "34-21",
  },
  {
    dimension: "38101100",
    programa: "CLPG LIDERAZGO Y DESARROLLO DE CAPACIDADES",
    fecha: "01/04/2021",
    factura: 594,
    proveedor: "PINZON ORBE FELIPE JAVIER",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "4 HORAS DE APOYO EN MODULO 4 EL 17 Y 19 DE MARZO",
    req: "30-21",
  },
  {
    dimension: "38101100",
    programa: "CLPG LIDERAZGO Y DESARROLLO DE CAPACIDADES",
    fecha: "3/17/2021",
    factura: 28,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "PAUTA DURANTE EL MES DE MARZO DEL PROGRAMA",
    req: "27-21",
  },
  {
    dimension: "38101100",
    programa: "CLPG LIDERAZGO Y DESARROLLO DE CAPACIDADES",
    fecha: "3/15/2021",
    factura: 422,
    proveedor: "RIVAS ORDOÑEZ LIBIA FERNANDA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "4 HORAS VIRTUALES DE CAPACITAICION EN EL MODULO 2",
    req: "22-21",
  },
  {
    dimension: "38101100",
    programa: "CLPG LIDERAZGO Y DESARROLLO DE CAPACIDADES",
    fecha: "3/15/2021",
    factura: 36,
    proveedor: "MOSCOSO MORENO ARTURO RENE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 100,
    iva: 12,
    valorConIva: "112",
    observacion: "2 HORAS VIRTUALES DEL MODULO 2",
    req: "23-21",
  },
  {
    dimension: "38101100",
    programa: "CLPG LIDERAZGO Y DESARROLLO DE CAPACIDADES",
    fecha: "12/03/2021",
    factura: 77,
    proveedor: "ALARCON SALVADOR MAURICIO MARTIN",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "4 HORAS VIRTUALES DE CAPACITACION EN EL MODULO 2",
    req: "21-21",
  },
  {
    dimension: "38101100",
    programa: "CLPG LIDERAZGO Y DESARROLLO DE CAPACIDADES",
    fecha: "12/14/2021",
    factura: 5731,
    proveedor: "ARIAS LONDOÑO MARIA ISABEL",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "4 HORAS DE CLASES VIRTUALES DEL MODULO 4",
    req: "211-20",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "10/15/2021",
    factura: 1229,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 435,
    iva: 12,
    valorConIva: "487,2",
    observacion: "PAUTAS DE MEDIOS PERFORMANCE INNOVACIÓN COMERCIAL SEPTIEMBRE",
    req: "204-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "10/13/2021",
    factura: 58,
    proveedor: "IN CONTAC",
    categoria: "MARKETING",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion: "PAUTAS EN LOS PROGRAMAS DE INNOVACIÓN COMERCIAL",
    req: "201-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "9/20/2021",
    factura: 1189,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 475,
    iva: 12,
    valorConIva: "532",
    observacion:
      "PAUTAS DE MEDIOS DE INNOVACION COMERCIAL ABRIL, PAUTA DE MEDIOS DIPLOMADO HABILIDADES DIRECTIVAS Y PAUTA DE MEDIOS GLOBALY COOL",
    req: "174-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "02/09/2021",
    factura: 52,
    proveedor: "IN CONTAC",
    categoria: "SERVICIOS TECNOLOGICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion: "FEE GESTIÓN COMERCIAL CALL CENTER MAB MES DE JUNIO 21",
    req: "154-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "07/10/2021",
    factura: 56,
    proveedor: "IN CONTAC",
    categoria: "SERVICIOS TECNOLOGICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion:
      "SE CANCELA A PROVEEDOR IN CONTAC POR SERVICIOS DE CALL CENTER DURANTE EL MES DE SEPTIEMBRE POR SERVICIO DE PAUTA EN EL PROGRAMA DE INNOVACION COMERCIAL",
    req: "195-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "9/13/2021",
    factura: 9377,
    proveedor: "RUIZ MACIAS DONNY MICHEL",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 74,
    iva: 12,
    valorConIva: "82,88",
    observacion: "PAGO POR 37 CERTIFICADOS",
    req: "169-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "07/09/2021",
    factura: 1183,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 635,
    iva: 12,
    valorConIva: "711,2",
    observacion: "PAUTA DE MEDIOS DE INNOVACION COMERCIAL ABRIL",
    req: "161-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "7/19/2021",
    factura: 1144,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 350,
    iva: 12,
    valorConIva: "392",
    observacion:
      "PAUTA DE MEDIOS INNOVACIÓN COMERCIAL ABRIL PAUTA DE MEDIOS DIPLOMADO EMPRENDIMIENTO BOOTCAMP PAUTA DE MEDIOS TRANSFORMACIÓN DIGITAL",
    req: "118-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "12/07/2021",
    factura: 47,
    proveedor: "IN CONTAC",
    categoria: "SERVICIOS TECNOLOGICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion:
      "SE CANCELA A PROVEEDOR IN CONTAC POR SERVICIOS DE CALL CENTER DURANTE EL MES DE JUNIO POR SERVICIO DE PAUTA EN LOS PROGRAMAS DE INNOVACIÓN COMERCIAL Y TRASNFORMACION DIGITAL",
    req: "106-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "6/17/2021",
    factura: 1118,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "611,8",
    iva: 12,
    valorConIva: "685,22",
    observacion:
      "PAGO POR PAUTA DE MEDIOS INNOVACIÓN COMERCIAL ABRIL Y PAUT DE MEDIOS DE TRANSFORMACIÓN DIGITAL",
    req: "86-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "5/18/2021",
    factura: 35,
    proveedor: "PAZ Y MIÑO LUIS EDUARDO IN CONTACT CENTER",
    categoria: "MARKETING",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion: "PAGO POR SERVICIO DE CALL CENTER DEL MES DE ABRIL",
    req: "50-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "4/16/2021",
    factura: 1055,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "410,41",
    iva: 12,
    valorConIva: "459,66",
    observacion: "PAGO A DAVCASTOR DIGITAL",
    req: "40-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "04/01/2021",
    factura: 27,
    proveedor: "PAZ Y MIÑO LUIS EDUARDO IN CONTACT CENTER",
    categoria: "MARKETING",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 325,
    iva: 12,
    valorConIva: "364",
    observacion: "PAGO POR SERVICIO DE CALL CENTER DEL MES DE MARZO",
    req: "31-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "3/17/2021",
    factura: 26,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "800,85",
    iva: 12,
    valorConIva: "896,95",
    observacion: "PAUTA CORRSPONDIENTE AL MES DE MARZO DEL PROGRAMA",
    req: "27-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "3/17/2021",
    factura: 26,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: 150,
    iva: 12,
    valorConIva: "168",
    observacion: "WEBINAR INNOVACION COMERCIAL",
    req: "27-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "03/03/2021",
    factura: 22,
    proveedor: "PAZ Y MIÑO LUIS EDUARDO IN CONTACT CENTER",
    categoria: "MARKETING",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 650,
    iva: 12,
    valorConIva: "728",
    observacion: "SERVICIOS DE CALL CENTER DURANTE EL MES DE FEBRERO",
    req: "18-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "2/17/2021",
    factura: 991,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "199,12",
    iva: 12,
    valorConIva: "223,01",
    observacion: "PAUTA PROGRAMA MES DE ENERO",
    req: "oct-21",
  },
  {
    dimension: "38101093",
    programa: "DIPLOMADO INNOVACION COMERCIAL",
    fecha: "5/19/2021",
    factura: 1092,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "UTPL",
    ciudad: "",
    valorSinIva: "857,48",
    iva: 12,
    valorConIva: "960,38",
    observacion: "PAGO POR PAUTA DIGITAL INNOVACION COMERCIAL",
    req: "55-21",
  },
  {
    dimension: "38101089",
    programa: "BOLSA DE VALORES  CONOCE NUESTRO MERCADO DE VALORES",
    fecha: "6/14/2021",
    factura: 131310,
    proveedor: "BOLSA DE VALORES QUITO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 80,
    iva: 12,
    valorConIva: "89,6",
    observacion:
      "SE REALIZA PAGO CORRESPONDIENTE A CAPACITACION DE 4 ESTUDIANTES EN EL CICLO 10 DEL 24 AL 30 DE MAYO",
    req: "78-21",
  },
  {
    dimension: "38101089",
    programa: "BOLSA DE VALORES  CONOCE NUESTRO MERCADO DE VALORES",
    fecha: "5/14/2021",
    factura: 128290,
    proveedor: "BOLSA DE VALORES QUITO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 160,
    iva: 12,
    valorConIva: "179,2",
    observacion:
      "SE REALIZA PAGO CORRESPONDIENTE A CAPACITACION DE 8 ESTUDIANTES EN EL CICLO 9 DEL 19 AL 25 DE ABRIL",
    req: "49-21",
  },
  {
    dimension: "38101089",
    programa: "BOLSA DE VALORES  CONOCE NUESTRO MERCADO DE VALORES",
    fecha: "04/08/2021",
    factura: 124520,
    proveedor: "BOLSA DE VALORES QUITO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 80,
    iva: 12,
    valorConIva: "89,6",
    observacion: "PAGO A LA BOLSA DE VALORES QUITO",
    req: "33-21",
  },
  {
    dimension: "38101089",
    programa: "BOLSA DE VALORES  CONOCE NUESTRO MERCADO DE VALORES",
    fecha: "01/03/2021",
    factura: 121640,
    proveedor: "BOLSA DE VALORES QUITO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 180,
    iva: 12,
    valorConIva: "201,6",
    observacion:
      "PAGO POR 9 ESTUDIANTES EN LA SEPTIMA EDICION DEL PROGRAMA CONOCE NUESTRO MERCADO DE VALORES",
    req: "15-20",
  },
  {
    dimension: "38101089",
    programa: "BOLSA DE VALORES  CONOCE NUESTRO MERCADO DE VALORES",
    fecha: "2/19/2021",
    factura: 120684,
    proveedor: "BOLSA DE VALORES QUITO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 140,
    iva: 12,
    valorConIva: "156,8",
    observacion:
      "PAGO POR 7 ESTUDIANTES EN LA SEXTA EDICION DEL PROGRAMA CONOCE NUESTRO MERCADO DE VALORES",
    req: "dic-21",
  },
  {
    dimension: "38101083",
    programa: "CLARO ESCUELA DE COMPETENCIAS",
    fecha: "5/20/2021",
    factura: 35,
    proveedor: "PEREZ GUZMAN ANAHI SUSANA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion: "PAGO ANAHI PEREZ APOYO ACADÉMICO MES DE MAYO",
    req: "61-21",
  },
  {
    dimension: "38101083",
    programa: "CLARO ESCUELA DE COMPETENCIAS",
    fecha: "4/20/2021",
    factura: 34,
    proveedor: "PEREZ GUZMAN ANAHI SUSANA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion: "PAGO ANAHI PEREZ APOYO ACADÉMICO MES DE ABRIL",
    req: "42-21",
  },
  {
    dimension: "38101083",
    programa: "CLARO ESCUELA DE COMPETENCIAS",
    fecha: "3/19/2021",
    factura: 33,
    proveedor: "PEREZ GUZMAN ANAHI SUSANA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion: "SERVICIO POR EL MES DE MARZO DEL 2021",
    req: "26-21",
  },
  {
    dimension: "38101083",
    programa: "CLARO ESCUELA DE COMPETENCIAS",
    fecha: "3/17/2021",
    factura: 56,
    proveedor: "VERA RAMOS EDISON ANDRES",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 8000,
    iva: 12,
    valorConIva: "8960",
    observacion:
      "VIRTUALIZACION DE COMPETENCIA 4 COMPETENCIAS (7, 8, 9 Y 10) AGUDEZA ANALITICA, ENFOQUE EN EL CLIENTE, MANEJA LA COMPLEJIDAD, DESARROLLO DEL TALENTO",
    req: "16-21",
  },
  {
    dimension: "38101083",
    programa: "CLARO ESCUELA DE COMPETENCIAS",
    fecha: "09/03/2021",
    factura: 32,
    proveedor: "PEREZ GUZMAN ANAHI SUSANA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion: "SERVICIO POR EL MES DE ENERO Y FEBRERO DEL 2021",
    req: "20-21",
  },
  {
    dimension: "38101126",
    programa: "AMCHAM INNOVACION COMERCIAL",
    fecha: "10/13/2021",
    factura: 510,
    proveedor: "FERNANDEZ ROMERO JOSE MIGUEL",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 250,
    iva: 12,
    valorConIva: "280",
    observacion: "HONORARIOS MASTERCLASS CRM Y SEGUIMIENTO AMCHAM MÓDULO 9",
    req: "200-21",
  },
  {
    dimension: "38101126",
    programa: "AMCHAM INNOVACION COMERCIAL",
    fecha: "7/15/2021",
    factura: 483,
    proveedor: "FERNANDEZ ROMERO JOSE MIGUEL",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "QUITO",
    valorSinIva: 250,
    iva: 12,
    valorConIva: "280",
    observacion:
      "HORA DE CLASE MAGISTRAL DEL MÓDULO ESTRATEGIA DIGITAL DE PROSPECCIÓN DEL PROGRAMA INNOVACIÓN COMERCIAL – AMCHAM",
    req: "113-21",
  },
  {
    dimension: "38101126",
    programa: "AMCHAM INNOVACION COMERCIAL",
    fecha: "7/16/2021",
    factura: 1835,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "QUITO",
    valorSinIva: 750,
    iva: 12,
    valorConIva: "840",
    observacion:
      "HORAS VIRTUALES DE MASTERCLASS DE LOS MÓDULOS: MOTIVACIÓN, ÉTICA Y LIDERAZGO PERSONAL; SERVICIO AL CLIENTE; TÉCNICAS DE VENTA CONSULTIVA",
    req: "115-21",
  },
  {
    dimension: "38101126",
    programa: "AMCHAM INNOVACION COMERCIAL",
    fecha: "5/18/2021",
    factura: 431,
    proveedor: "CALVOPIÑA HEREDIA SANTIAGO DANIEL",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion:
      "PAGO POR SEGUIMIENTO EN PLATAFORMA MODULO CREATIVIDAD E INNOVACION",
    req: "51-21",
  },
  {
    dimension: "38101126",
    programa: "AMCHAM INNOVACION COMERCIAL",
    fecha: "5/18/2021",
    factura: 431,
    proveedor: "CALVOPIÑA HEREDIA SANTIAGO DANIEL",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "FEDES",
    ciudad: "",
    valorSinIva: 50,
    iva: 12,
    valorConIva: "56",
    observacion:
      "PAGO POR SEGUIMIENTO EN PLATAFORMA MODULO CREATIVIDAD E INNOVACION",
    req: "51-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "10/21/2021",
    factura: 3,
    proveedor: "BARBA OCHOA DAVID FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 600,
    iva: 12,
    valorConIva: "672",
    observacion:
      "PAGO POR APOYO EN EL ÁREA COMERCIAL DESDE EL 16 DE SEPIEMBRE AL 16 DE OCTUBRE DEL 2021",
    req: "215-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "04/10/2021",
    factura: 7559,
    proveedor: "VELASQUEZ VERONICA",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: "4,46",
    iva: 12,
    valorConIva: "5",
    observacion: "PAGO POR RECARGA DE 5 DOLARES A LUIS  ACOSTA",
    req: "192-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "01/10/2021",
    factura: 77542,
    proveedor: "VELASQUEZ VERONICA",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: "4,46",
    iva: 12,
    valorConIva: "5",
    observacion: "PAGO POR RECARGA DE 5 DOLARES A GABRIELA VASQUEZ",
    req: "191-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "9/20/2021",
    factura: 1,
    proveedor: "BARBA OCHOA DAVID FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 625,
    iva: 12,
    valorConIva: "700",
    observacion:
      "PAGO POR APOYO EN EL ÁREA COMERCIAL DESDE EL 16 DE AGOSTO AL 16 DE SEPTIEMBRE DEL 2021",
    req: "171-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "9/20/2021",
    factura: 1862,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 300,
    iva: 12,
    valorConIva: "336",
    observacion:
      "PAGO POR 6 HORAS DE CAPACITACIÓN EN EL PROGRAMA DE LIDERAZGO (6 DIAS)",
    req: "170-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "9/14/2021",
    factura: 271855,
    proveedor: "VELASQUEZ VERONICA",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: "4,46",
    iva: 12,
    valorConIva: "5",
    observacion: "RECARGA DE APOYO LOGÍTICO",
    req: "168-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "08/09/2021",
    factura: 2356230,
    proveedor: "VELASQUEZ VERONICA",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: "4,46",
    iva: 12,
    valorConIva: "5",
    observacion: "RECARGA DE APOYO LOGÍTICO",
    req: "164-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "08/09/2021",
    factura: 18329,
    proveedor: "VELASQUEZ VERONICA",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: "4,46",
    iva: 12,
    valorConIva: "5",
    observacion: "COMPRA DE CHIP PARA PERSONA DE APOYO LOGÍSTICO",
    req: "164-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "7/19/2021",
    factura: 1113,
    proveedor: "MILA ALMACHE OSCAR",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 55,
    iva: 12,
    valorConIva: "61,6",
    observacion:
      "KITS DE REGALOS CON ESFERO, JARRO Y CAJA DE CARTÓN PARA ENTREGA EN GRADUACIÓN MBA PRESENCIAL CORTE 2",
    req: "120-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "11/05/2021",
    factura: 63,
    proveedor: "AGUILAR PALACIOS MARIA CAMILA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 900,
    iva: 12,
    valorConIva: "1008",
    observacion:
      "SERVICIOS DIVERSOS DE COORDINACION DE PROYECTOS DEL AÑO 2020 (BONO)",
    req: "48-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "4/29/2021",
    factura: null,
    proveedor: "PRENDHO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 4200,
    iva: 0,
    valorConIva: "4200",
    observacion: "50% POR MENTORIAS REALIZADAS EN EL PROGRAMA",
    req: "43-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "01/03/2021",
    factura: 616,
    proveedor: "MUÑOZ VALENCIA RODRIGO ANDRES",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 2000,
    iva: 12,
    valorConIva: "2240",
    observacion:
      "GESTION DE IMPLEMENTACION DEL PROYECTO MARATON DE LAS IDEAS 50% RESTANTE",
    req: "13-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "1/18/2021",
    factura: null,
    proveedor: "PRENDHO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 4200,
    iva: 0,
    valorConIva: "4200",
    observacion:
      "PAGO POR ETAPA DE MENTORIAS A LOS 20 EMPRESNDIMIENTOS GANADORES DE LA CONVOCATORIA (160 HORAS)",
    req: "ene-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "04/06/2021",
    factura: 65,
    proveedor: "AGUILAR PALACIOS MARIA CAMILA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 300,
    iva: 12,
    valorConIva: "336",
    observacion:
      "SERVICIOS DIVERSOS DE COORDINACION DE PROYECTO CARGIL (BONO POR CUMPLIIENTO EN PROGRAMA)",
    req: "67-21",
  },
  {
    dimension: "AUTOG004",
    programa: "HACKATHON BOOTCAMP EMPRENDIMIENTO",
    fecha: "03/06/2021",
    factura: 28,
    proveedor: "VILLALVA CHAVEZ JUAN PABLO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 1100,
    iva: 12,
    valorConIva: "1232",
    observacion:
      "DESARROLLO DE UN DASHBOARD PANEL DE CONTROL CON POWER BI PARA EL AREA FINANCIERA",
    req: "70-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "12/10/2021",
    factura: 40,
    proveedor: "ACOSTA MUÑOZ LUIS ENRIQUE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion:
      "SERVIO DE LLAMADAS TELEFONICAS Y APOYO EN SEGUIMIENTO EN EL PROGRAMA DE MUJERES EMPRESARIAS DE CARGUILL DESDE EL 2 DE AGOSTO HASTA EL 3 DE SEPTIEMBRE",
    req: "198-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "05/07/2021",
    factura: 5,
    proveedor: "SUAREZ MURILLO MARINA PENELOPE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 20,
    iva: 12,
    valorConIva: "22,4",
    observacion:
      "4 HORAS DE APOYO LOGÍSTICO DEL PROGRAMA MUJERES EMPRESARIAS CARGILL",
    req: "99-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "8/23/2021",
    factura: 42,
    proveedor: "PEREZ GUZMAN ANAHI SUSANA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 600,
    iva: 12,
    valorConIva: "672",
    observacion:
      "SERVICIO DE APOYO AL DEPARTAMENTO ACADEMICO MES DE JULIO-AGOSTO 2021",
    req: "146-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "01/07/2021",
    factura: 37,
    proveedor: "PEREZ GUZMAN ANAHI SUSANA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion: "SERVICIO DE APOYO A DEPARTAMENTO ACADÉMICO DE JUNIO 2021",
    req: "92-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "08/04/2021",
    factura: 28,
    proveedor: "APOLO PIEDRA KARLA KIMBERLY",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 525,
    iva: 12,
    valorConIva: "588",
    observacion:
      "SEGUIMIENTO ACADEMICO EDUCACION CONTINUA DEL 26 DE ABRIL AL 28 DE MAYO",
    req: "138-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "08/04/2021",
    factura: 8,
    proveedor: "SUAREZ MURILLO MARINA PENELOPE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 100,
    iva: 12,
    valorConIva: "112",
    observacion:
      "20 HORAS DE APOYO LOGISTICO DEL GRUPO 4 EL 2, 3, 30 Y 31 DE JULIO",
    req: "137-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "08/04/2021",
    factura: 8,
    proveedor: "SUAREZ MURILLO MARINA PENELOPE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 80,
    iva: 12,
    valorConIva: "89,6",
    observacion:
      "16 HORAS DE APOYO LOGISTICO DEL GRUPO 3 EL 2, 3, 30 Y 31 DE JULIO",
    req: "137-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "08/04/2021",
    factura: 36,
    proveedor: "ACOSTA MUÑOZ LUIS ENRIQUE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 130,
    iva: 12,
    valorConIva: "145,6",
    observacion:
      "26 HORAS DE APOYO LOGISTICO PREOGRAMA TRANSFORMACION UTPL DEL 25 MAYO AL 16 DE JUNIO",
    req: "136-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "08/04/2021",
    factura: 35,
    proveedor: "ACOSTA MUÑOZ LUIS ENRIQUE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 130,
    iva: 12,
    valorConIva: "145,6",
    observacion:
      "26 HORAS DE APOYO LOGISTICO DEL GRUPO 1 DEL 22 DE MAYO AL 10 DE JULIO",
    req: "136-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "08/04/2021",
    factura: 33,
    proveedor: "ACOSTA MUÑOZ LUIS ENRIQUE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 130,
    iva: 12,
    valorConIva: "145,6",
    observacion:
      "26 HORAS DE APOYO LOGISTICO DEL GRUPO 2 DEL 5 DE JUNIO AL 24 DE JULIO",
    req: "136-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "08/04/2021",
    factura: 182,
    proveedor: "SALAZAR ALMEIDA JUAN FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 250,
    iva: 12,
    valorConIva: "280",
    observacion: "DISEÑO INSTRUCCIONAL DEL MÓDULO: CULTURA DIGITAL",
    req: "135-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "08/04/2021",
    factura: 182,
    proveedor: "SALAZAR ALMEIDA JUAN FERNANDO",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 960,
    iva: 12,
    valorConIva: "1075,2",
    observacion: "16 HORAS VIRULAES DEL MODULO DIGITAL DEL 1O Y 11 DE JUNIO",
    req: "135-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "08/04/2021",
    factura: 18273,
    proveedor: "PACARI",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: "61,92",
    iva: 12,
    valorConIva: "69,35",
    observacion: "12 COMBOS CATA PACARI PARA PERSONAL ADMINISTRATIVO",
    req: "132-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "7/19/2021",
    factura: 28,
    proveedor: "GILD SANTIAGO JOSE ANTONIO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 250,
    iva: 12,
    valorConIva: "280",
    observacion:
      "DISEÑO INSTRUCCIONAL DEL MÓDULO: FINANZAS PARA EMPRENDEDORES – PROGRAMA MUJERES EMPRESARIAS CARGILL",
    req: "121-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "7/19/2021",
    factura: 29,
    proveedor: "GILD SANTIAGO JOSE ANTONIO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 960,
    iva: 12,
    valorConIva: "1075,2",
    observacion:
      "HORAS DE CLASES VIRTUALES DEL MÓDULO FINANZAS PARA EMPRENDEDORES – PROGRAMA MUJERES EMPRESARIAS CARGILL",
    req: "121-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "12/07/2021",
    factura: 1642702,
    proveedor: "FYBECA",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: "8,92",
    iva: 12,
    valorConIva: "9,99",
    observacion:
      "REEMBOLSO POR LA COMPRA DE 2 CHIPS TELEFÓNICOS PARA EL DEPARTAMENTO INCOMPANYS.",
    req: "104-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "12/07/2021",
    factura: 21,
    proveedor: "ABAD CHIRIBOGA EDUARDO ALFREDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 525,
    iva: 12,
    valorConIva: "588",
    observacion:
      "SERVICIOS PRESTADOS SEGUIMIENTO ACADÉMICO DEL 2 DE ABRIL AL 7 DE MAYO EL RUBRO DE GASTO FEE EDUCACION CONTINUA",
    req: "102-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "06/07/2021",
    factura: 1828,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 1210,
    iva: 12,
    valorConIva: "1355,2",
    observacion:
      "HORAS DE TALLER DEL MÓDULO 1 LIDERAZ PERSONAL Y MOTIVACIÓN DEL PROGRAM MUJERES EMPRESARIAS – CARGILL GRUPO 1, GRUPO 2, GRUPO 3 Y GRUPO 4",
    req: "100-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "05/07/2021",
    factura: 5,
    proveedor: "SUAREZ MURILLO MARINA PENELOPE",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 30,
    iva: 12,
    valorConIva: "33,6",
    observacion:
      "6 HORAS DE APOYO LOGÍSTICO DEL PROGRAMA MUJERES EMPRESARIAS CARGILL",
    req: "99-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "5/19/2021",
    factura: 1093,
    proveedor: "DAVCASTOR DIGITAL SA.",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: "202,34",
    iva: 12,
    valorConIva: "226,62",
    observacion:
      "PAUTA MEDIOS MUJERES EMPRESARIAS DEL PROGRAMA CARGILL DEL MES DE ABRIL",
    req: "57-21",
  },
  {
    dimension: "AUTOG006",
    programa: "CARGILL MUJERES EMPRESARIAS",
    fecha: "5/18/2021",
    factura: 36,
    proveedor: "PAZ Y MIÑO LUIS EDUARDO IN CONTACT CENTER",
    categoria: "MARKETING",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 738,
    iva: 12,
    valorConIva: "826,56",
    observacion:
      "LEVANTAMIENTO DE DATOS Y LLAMADAS INTERNACIONALES A MUJERES EMPRESARIAS",
    req: "52-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "9/20/2021",
    factura: 79,
    proveedor: "GONZALEZ HUERTA MARIA ESTHER",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 3200,
    iva: 12,
    valorConIva: "3584",
    observacion:
      "60 HORAS DE CLASES MÓDULOS BOOTCAMP EMPRENDIMIENTO PROYECTO ECUADOR VENEUELA CORPEI Y CONSTRUCCIÓN DE MATERIAL DEL MISMO MÓDULO",
    req: "178-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "9/14/2021",
    factura: 174811,
    proveedor: "VELASQUEZ ALVAREZ VERONICA ALEXANDRA",
    categoria: "MATERIAL DE ESTUDIO",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: "21,41",
    iva: 12,
    valorConIva: "23,98",
    observacion:
      "REEMBOLSO POR LA COMPRA DE UNA FLASH PARA ENVIAR INFORMES DEL PROGRAMA CORPEI A CLIENTE",
    req: "172-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "06/09/2021",
    factura: 74,
    proveedor: "AGUILAR PALACIOS MARIA CAMILA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 450,
    iva: 12,
    valorConIva: "504",
    observacion:
      "SERVICIOS LOGISTICOS EN PROYECTO CORPEI POR EL MES DE JUNIO, JULIO AGOSTO Y SEPTIEMBRE",
    req: "155-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "01/09/2021",
    factura: 30,
    proveedor: "GILD SANTIAGO JOSE ANTONIO",
    categoria: "",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 4640,
    iva: 12,
    valorConIva: "5196,8",
    observacion: "SERVICIOS DE CAPACITACION, WEBINAR Y DISEÑO DE MATERIAL",
    req: "148-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "7/19/2021",
    factura: 40,
    proveedor: "PEREZ GUZMAN ANAHI SUSANA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 310,
    iva: 12,
    valorConIva: "347,2",
    observacion:
      "HORAS DE APOYO LOGÍSTICO EN EL PROGRAMA ECUADOR-VENEZUELA “CREANDO OPORTUNIDADES DE PROSPERIDAD” CORPEI",
    req: "98-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "6/18/2021",
    factura: 58,
    proveedor: "RUIZ VELEZ PABLO FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 60,
    iva: 12,
    valorConIva: "67,2",
    observacion: "2 HORAS DE WEBINAR IMPARTIDOS PARA LOS GRUPOS 21",
    req: "84-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "6/18/2021",
    factura: 58,
    proveedor: "RUIZ VELEZ PABLO FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 500,
    iva: 12,
    valorConIva: "560",
    observacion: "10 HORAS DE WEBINAR IMPARTIDOS PARA LOS GRUPOS 5,17,18,19,20",
    req: "84-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "6/18/2021",
    factura: 1825,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 120,
    iva: 12,
    valorConIva: "134,4",
    observacion: "4 HORAS DE TALLERES MODULO 1 GRUPOS 21",
    req: "81-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "6/18/2021",
    factura: 1825,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 1440,
    iva: 12,
    valorConIva: "1612,8",
    observacion: "24 HORAS DE TALLERES MODULO 1 GRUPOS 15,16,17,18,19,20",
    req: "81-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "04/06/2021",
    factura: 64,
    proveedor: "AGUILAR PALACIOS MARIA CAMILA",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 450,
    iva: 12,
    valorConIva: "504",
    observacion: "SERVICIOS LOGISTICOS EN PROYECTO",
    req: "68-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "5/25/2021",
    factura: 57,
    proveedor: "RUIZ VELEZ PABLO FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 400,
    iva: 12,
    valorConIva: "448",
    observacion: "8 HORAS DE WEBINAR IMPARTIDOS EN EL PROGRAMA EUADOR VENZUELA",
    req: "45-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "5/20/2021",
    factura: 1813,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 1680,
    iva: 12,
    valorConIva: "1881,6",
    observacion:
      "28 HORAS DE TALLER DEL MODULO 1 DE LOS DIAS 9,10,11,12,13,14 Y 15",
    req: "58-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "5/20/2021",
    factura: 55,
    proveedor: "RUIZ VELEZ PABLO FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 700,
    iva: 12,
    valorConIva: "784",
    observacion:
      "14 HORAS DE WEBINAR IMPARTIDOS EN EL PROGRAMA ECUADOR VENEZUELA LOS DIAS 21, 23, 27, 04, 11, Y 17 DE ABRIL Y MAYO",
    req: "60-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "4/20/2021",
    factura: 1806,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 960,
    iva: 12,
    valorConIva: "1075,2",
    observacion: "16 HONORARIOS CORPEI GRUPOS 4,6,7 Y 8",
    req: "41-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "04/06/2021",
    factura: 53,
    proveedor: "RUIZ VELEZ PABLO FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "Diseño de material para el módulo Webinar\n$200",
    req: "32-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "05/06/2021",
    factura: 53,
    proveedor: "RUIZ VELEZ PABLO FERNANDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 400,
    iva: 12,
    valorConIva: "448",
    observacion:
      "8 Horas de webinar impartidos en el programa Ecuador-Venezuela “Creando oportunidad",
    req: "32-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "3/19/2021",
    factura: 1798,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 200,
    iva: 12,
    valorConIva: "224",
    observacion: "diseño de material",
    req: "25-21",
  },
  {
    dimension: "AUTOG007",
    programa:
      "AUTOGESTION CORPEI ECUADOR VENEZUELA OPORTUNIDADES DE PROSPERIDAD",
    fecha: "3/19/2021",
    factura: 1798,
    proveedor: "CASTRO VALENCIA SANTIAGO EDUARDO",
    categoria: "HONORARIOS ACADEMICOS",
    responsable: "AUTO",
    ciudad: "",
    valorSinIva: 720,
    iva: 12,
    valorConIva: "806,4",
    observacion: "12 HORAS DE TALLERES MODULO 1 GRUPOS 1, 2 Y 3",
    req: "25-21",
  },
];

export const addGastos = async (): Promise<void> => {
  let contador = 1;
  for (const gasto of gastos) {
    const response = await createGasto({
      ...gasto,
      valorConIva: parseFloat(gasto.valorConIva.toString().replace(",", ".")),
      valorSinIva: parseFloat(gasto.valorSinIva.toString().replace(",", ".")),
      fecha: new Date(gasto.fecha),
      factura: (gasto.factura || "").toString(),
    });
    (async () => await new Promise((resolve) => setTimeout(resolve, 1000)))();
    if (!response.state) {
      console.debug("error en", contador, response.message);
    } else {
      console.debug("correcto");
    }
    contador += 1;
  }
};
